services:
  - type: web
    name: beauty-salon-backend
    env: node
    branch: main
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FRONTEND_URL
        sync: false
